# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7f2c6c3ee8bc5011b972bb6a49b10b13454de2b66ae1fffc7ea08dbcf1f33b3b7c9acb5f980e0884db48d1769d73ea205c7907d97eab00d7bc7a8f592d2c04c

test:
  secret_key_base: d4ca2fd7ba35cb3efa7f1afcdfaa3fffc1e621c0c51461d74e0ec07cc237fc9221616654e93e2ceee2c5a9f973fbf9e08c4799d3c6ea3986e2cb398b1cc706cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
