AllCops:
  Exclude:
    - 'vendor/**/*'
  DisplayCopNames: true

Rails:
  Enabled: true

inherit_from:
  - https://github.com/actcat/sideci_rails_sandbox/blob/test/rubocop/.rubocop.yml
  - ../.rubocop.yml

inherit_gem:
  onkcop: "config/rubocop.yml"
>>>>>>> add inhert_gem, inherit_from
